-- VERIFICANDO SE HÁ DADOS DUPLICADOS
SELECT loan_id, COUNT(LOAN_ID) AS CONTAGEM
FROM emprestimos
GROUP BY loan_id
ORDER BY COUNT(loan_id) DESC;

-- A COLUNA loan_id PERMITE A INSERÇÃO DE DADOS NULL, O QUE NÃO ACEITO PARA O CADASTRO DE CHAVES PRIMÁRIAS, PORTANTO É NECESSÁRIO
-- MODIFICAR ESTA COLUNA PARA NOT NULL.

ALTER TABLE emprestimos
ALTER COLUMN loan_id VARCHAR(16) NOT NULL;

-- CRIANDO A CHAVE PRIMÁRIA.

ALTER TABLE emprestimos
ADD CONSTRAINT PK_emprestimos
PRIMARY KEY (loan_id);