-- PROCEDIMENTO PARA VERIFICAR SE HÁ ENTRADAS REPETIDAS NA COLUNA PERSON_ID, QUE SERÁ UTILIZADA COMO PRIMARY KEY DA TABELA.
SELECT person_id, COUNT(PERSON_ID) AS CONTAGEM 
FROM dados_mutuarios
GROUP BY PERSON_ID
ORDER BY COUNT(PERSON_ID) DESC;

-- FOI CONSTATADO QUE EXISTEM CAMPOS NÃO PREENCHIDOS E QUE SE REPETEM POR 4 VEZES. LEVANDO EM CONSIDERAÇÃO QUE ESTA COLUNA SE TRATA
-- DE ELEMENTOS DE IDENTIFICAÇÃO DO CLIENTE, NÃO FAZ SENTIDO PARA AS ANÁLISES QUE SE SEGUIREM NESTE PROJETO, MANTER ESTES 4 CONJUNTOS DE DADOS,
-- PORTANTO SERÁ REALIZADO A LIMPEZA DA TABELA DADOS_MUTUARIOS A PARTIR DA REMOÇÃO DESTAS ENTRADAS.

DELETE FROM dados_mutuarios
WHERE PERSON_ID = '';

-- COM OS DADOS CORRIGIDOS, PODEMOS ATRIBUIR A COLUNO PERSON_ID A CONDIÇÃO DE PK.

ALTER TABLE dados_mutuarios
ADD CONSTRAINT PK_dados_mutuarios
PRIMARY KEY (person_id);



